# Generated by Django 4.0.3 on 2022-10-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_customuserprofile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='created_at',
        ),
    ]
